name: Auto Tag Minor

on:
  push:
    branches: [ "master" ]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest=$(git tag --list 'v*' --sort=-v:refname | head -n 1)
          echo "latest_tag=$latest" >> $GITHUB_OUTPUT

      - name: Calculate next minor version
        id: bump_minor
        run: |
          latest=${{ steps.get_tag.outputs.latest_tag }}
          if [[ "$latest" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
            new_minor=$((minor + 1))
            new_tag="v${major}.${new_minor}.0"
          else
            new_tag="v1.0.0"
          fi
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create new tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.bump_minor.outputs.new_tag }}
          git push origin ${{ steps.bump_minor.outputs.new_tag }}
